# Generated by Django 5.1.1 on 2026-01-05 23:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_datecompleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatosPersonales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcionperfil', models.CharField(blank=True, max_length=50)),
                ('perfilactivo', models.IntegerField(default=1)),
                ('apellidos', models.CharField(max_length=60)),
                ('nombres', models.CharField(max_length=60)),
                ('nacionalidad', models.CharField(blank=True, max_length=20)),
                ('lugarnacimiento', models.CharField(blank=True, max_length=60)),
                ('fechanacimiento', models.DateField(blank=True, null=True)),
                ('numerocedula', models.CharField(max_length=10, unique=True)),
                ('sexo', models.CharField(choices=[('H', 'Hombre'), ('M', 'Mujer')], max_length=1)),
                ('estadocivil', models.CharField(blank=True, max_length=50)),
                ('licenciaconducir', models.CharField(blank=True, max_length=6)),
                ('telefonoconvencional', models.CharField(blank=True, max_length=15)),
                ('telefonofijo', models.CharField(blank=True, max_length=15)),
                ('direcciontrabajo', models.CharField(blank=True, max_length=50)),
                ('direcciondomiciliaria', models.CharField(blank=True, max_length=50)),
                ('sitioweb', models.CharField(blank=True, max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='CursoRealizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombrecurso', models.CharField(max_length=100)),
                ('fechainicio', models.DateField(blank=True, null=True)),
                ('fechafin', models.DateField(blank=True, null=True)),
                ('totalhoras', models.IntegerField(blank=True, null=True)),
                ('descripcioncurso', models.CharField(blank=True, max_length=100)),
                ('entidadpatrocinadora', models.CharField(blank=True, max_length=100)),
                ('nombrecontactoauspicia', models.CharField(blank=True, max_length=100)),
                ('telefonocontactoauspicia', models.CharField(blank=True, max_length=60)),
                ('emailempresapatrocinadora', models.EmailField(blank=True, max_length=254)),
                ('activarparaqueseveaenfront', models.BooleanField(default=True)),
                ('rutacertificado', models.CharField(blank=True, max_length=100)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursos', to='tasks.datospersonales')),
            ],
        ),
        migrations.CreateModel(
            name='ExperienciaLaboral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargodesempenado', models.CharField(max_length=100)),
                ('nombrempresa', models.CharField(max_length=50)),
                ('lugarempresa', models.CharField(blank=True, max_length=50)),
                ('emailempresa', models.EmailField(blank=True, max_length=254)),
                ('sitiowebempresa', models.CharField(blank=True, max_length=100)),
                ('nombrecontactoempresarial', models.CharField(blank=True, max_length=100)),
                ('telefonocontactoempresarial', models.CharField(blank=True, max_length=60)),
                ('fechainiciogestion', models.DateField(blank=True, null=True)),
                ('fechafingestion', models.DateField(blank=True, null=True)),
                ('descripcionfunciones', models.CharField(blank=True, max_length=100)),
                ('activarparaqueseveaenfront', models.BooleanField(default=True)),
                ('rutacertificado', models.CharField(blank=True, max_length=100)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiencias', to='tasks.datospersonales')),
            ],
        ),
        migrations.CreateModel(
            name='ProductoAcademico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombrerecurso', models.CharField(max_length=100)),
                ('clasificador', models.CharField(blank=True, max_length=100)),
                ('descripcion', models.CharField(blank=True, max_length=100)),
                ('activarparaqueseveaenfront', models.BooleanField(default=True)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos_academicos', to='tasks.datospersonales')),
            ],
        ),
        migrations.CreateModel(
            name='Reconocimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiporeconocimiento', models.CharField(max_length=100)),
                ('fechareconocimiento', models.DateField(blank=True, null=True)),
                ('descripcionreconocimiento', models.CharField(blank=True, max_length=100)),
                ('entidadpatrocinadora', models.CharField(blank=True, max_length=100)),
                ('nombrecontactoauspicia', models.CharField(blank=True, max_length=100)),
                ('telefonocontactoauspicia', models.CharField(blank=True, max_length=60)),
                ('activarparaqueseveaenfront', models.BooleanField(default=True)),
                ('rutacertificado', models.CharField(blank=True, max_length=100)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reconocimientos', to='tasks.datospersonales')),
            ],
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
