# Generated by Django 5.1.1 on 2026-01-26 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_rename_descripcioncurso_cursorealizado_descripcion_curso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datospersonales',
            name='foto_url',
            field=models.URLField(blank=True),
        ),
    ]
