# Generated by Django 5.1.1 on 2026-01-28 06:19

import django.core.validators
import tasks.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_ventagarage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursorealizado',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True, validators=[tasks.models.no_futuro]),
        ),
        migrations.AlterField(
            model_name='cursorealizado',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True, validators=[tasks.models.no_futuro]),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='fechana_de_nacimiento',
            field=models.DateField(blank=True, null=True, validators=[tasks.models.no_futuro]),
        ),
        migrations.AlterField(
            model_name='experiencialaboral',
            name='fecha_de_inicio_de_gestion',
            field=models.DateField(blank=True, null=True, validators=[tasks.models.no_futuro]),
        ),
        migrations.AlterField(
            model_name='experiencialaboral',
            name='fecha_fin_de_gestion',
            field=models.DateField(blank=True, null=True, validators=[tasks.models.no_futuro]),
        ),
        migrations.AlterField(
            model_name='reconocimiento',
            name='fecha_reconocimiento',
            field=models.DateField(blank=True, null=True, validators=[tasks.models.no_futuro]),
        ),
        migrations.AlterField(
            model_name='ventagarage',
            name='valordelbien',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddConstraint(
            model_name='ventagarage',
            constraint=models.CheckConstraint(condition=models.Q(('valordelbien__gte', 0)), name='venta_valor_no_negativo'),
        ),
    ]
