# Generated by Django 5.1.1 on 2026-01-28 06:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_alter_cursorealizado_fecha_fin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursorealizado',
            name='total_horas',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddConstraint(
            model_name='cursorealizado',
            constraint=models.CheckConstraint(condition=models.Q(('total_horas__gte', 0), ('total_horas__isnull', True), _connector='OR'), name='curso_total_horas_no_negativo'),
        ),
    ]
