# Generated by Django 5.1.1 on 2026-01-28 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_alter_cursorealizado_total_horas_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=160)),
                ('tipo', models.CharField(choices=[('PROYECTO', 'PROYECTO'), ('CURSO', 'CURSO'), ('CERTIFICACION', 'CERTIFICACIÓN'), ('TITULO', 'TÍTULO'), ('OTRO', 'OTRO')], default='PROYECTO', max_length=20)),
                ('descripcion', models.TextField(blank=True)),
                ('activarparaqueseveaenfront', models.BooleanField(default=True)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formacion_items', to='tasks.datospersonales')),
            ],
        ),
    ]
