# Generated by Django 5.1.1 on 2026-01-28 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_formacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventagarage',
            name='imagen_url',
            field=models.URLField(blank=True),
        ),
    ]
