# Generated by Django 5.1.1 on 2026-01-28 16:19

import tasks.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_ventagarage_imagen_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoacademico',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True, validators=[tasks.models.no_futuro]),
        ),
    ]
